
parameters:
  name: ''
  vmImage: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    VIRTUALENV: 'testvenv'
    JUNITXML: 'test-data.xml'
    LOKY_MAX_DEPTH: 5
    COVERAGE_PROCESS_START: '.coveragerc'
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: Use cached Python $(python.version) for tests.

    - script: python -m pip install --upgrade tox
      displayName: Install Python-based tools.

    - script: tox -e $(tox.env)
      displayName: 'Run Tox'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '$(JUNITXML)'
        testRunTitle: ${{ format('{0}-$(Agent.JobName)', parameters.name) }}
      displayName: 'Publish Test Results'
      condition: succeededOrFailed()
    - script: |
        continuous_integration\\azure\\upload_codecov.cmd
      displayName: 'Upload to codecov'
      condition: succeeded()
