
parameters:
  name: ''
  vmImage: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: $(imageName)
  variables:
    VIRTUALENV: 'testvenv'
    JUNITXML: 'test-data.xml'
    LOKY_MAX_DEPTH: 5
    COVERAGE_PROCESS_START: '.coveragerc'
    OMP_NUM_THREADS: 4
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: Use cached Python $(python.version) for tests.

    - script: python -m pip install --upgrade tox
      displayName: Install Python-based tools.

    - script: |
        bash continuous_integration/travis/runtests.sh
      displayName: 'Run Tox'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '$(JUNITXML)'
        testRunTitle: ${{ format('{0}-$(Agent.JobName)', parameters.name) }}
      displayName: 'Publish Test Results'
      condition: succeededOrFailed()
    - bash: |
        curl -s https://codecov.io/bash | bash
      displayName: 'Upload to codecov'
      condition: succeeded()
