jobs:
- job: 'test_loky'
  strategy:
    matrix:

      windows-py38:
        imageName: "vs2017-win2016"
        python.version: "3.8"
        tox.env: py38
      windows-py35:
        imageName: "vs2017-win2016"
        python.version: "3.5"
        tox.env: py35
      windows-py27:
        imageName: "vs2017-win2016"
        python.version: "2.7"
        tox.env: py27

      macos-py38:
        imageName: "macos-10.14"
        python.version: "3.8"
        tox.env: py38
      macos-py35:
        imageName: "macos-10.14"
        python.version: "3.5"
        tox.env: py35
      macos-py27-high-memory:
        imageName: "macos-10.14"
        python.version: "2.7"
        tox.env: py27
        RUN_MEMORY: "true"

      linux-pypy3:
        imageName: "ubuntu-20.04"
        python.version: "pypy3"
        tox.env: pypy3
        LOKY_MAX_CPU_COUNT: "2"

      linux-python-nightly:
        imageName: "ubuntu-20.04"
        python.version: "3.9"
        tox.env: py39
      linux-py38-joblib-tests:
        imageName: "ubuntu-20.04"
        python.version: "3.8"
        tox.env: "py38"
        joblib.tests: "true"
      linux-py38-high-memory:
        imageName: "ubuntu-20.04"
        python.version: "3.8"
        tox.env: py38
        RUN_MEMORY: "true"
      linux-py37:
        imageName: "ubuntu-20.04"
        python.version: "3.7"
        tox.env: py37
      linux-py36:
        imageName: "ubuntu-20.04"
        python.version: "3.6"
        tox.env: py36
      linux-py35:
        imageName: "ubuntu-20.04"
        python.version: "3.5"
        tox.env: py35
      linux-py27:
        imageName: "ubuntu-20.04"
        python.version: "2.7"
        tox.env: py27

  pool:
    vmImage: $(imageName)
  variables:
    JUNITXML: 'test-data.xml'
    PYTEST_ARGS: '-vl --timeout=60 --maxfail=5'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'
      condition: ne(variables['python.version'], '3.9')
    - bash: |
        sudo add-apt-repository ppa:deadsnakes/nightly
        sudo apt update
        sudo apt install python3.9 python3.9-venv python3.9-dev
        python3.9 -m venv nightly-venv
        echo "##vso[task.prependpath]nightly-venv/bin"
      displayName: Install Python 3.9 from ppa:deadsnakes/nightly
      condition: eq(variables['python.version'], '3.9')
    # azure-pipelines unpredictably switches between Git\bin\bash and
    # Git\usr\bin\bash when running a bash script inside Windows environments.
    # The latter may use wrong bash commands, resulting in errors when codecov
    # tries to upload the coverage results.
    - bash: echo "##vso[task.prependpath]C:/Program Files/Git/bin"
      displayName: 'Override Git bash shell for Windows'
      condition: eq(variables['Agent.OS'], 'Windows_NT')

    - script: python -m pip install --upgrade tox
      displayName: 'Install tox'

    - script: |
        bash continuous_integration/runtests.sh
      displayName: 'Test loky'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '$(JUNITXML)'
      displayName: 'Publish Test Results'
      condition: succeededOrFailed()

    - bash: |
        curl -s https://codecov.io/bash | bash
      displayName: 'Upload to codecov'
      condition: and(succeeded(), ne(variables['joblib.tests'], 'true'))
