jobs:
- job: 'test_loky'
  strategy:
    matrix:

      windows-py310:
        imageName: windows-latest
        python.version: "3.10"
        tox.env: py310
      windows-py37:
        imageName: windows-latest
        python.version: "3.7"
        tox.env: py37

      macos-py310:
        imageName: "macos-10.15"
        python.version: "3.10"
        tox.env: py310
      macos-py37:
        imageName: "macos-10.15"
        python.version: "3.7"
        tox.env: py37

      linux-pypy3:
        imageName: "ubuntu-20.04"
        python.version: "pypy3"
        tox.env: pypy3
        LOKY_MAX_CPU_COUNT: "2"

      linux-py310:
        imageName: "ubuntu-20.04"
        python.version: "3.10"
        tox.env: py310
      linux-py39-joblib-tests:
        imageName: "ubuntu-20.04"
        python.version: "3.9"
        tox.env: "py39"
        joblib.tests: "true"
      linux-python-py38-high-memory:
        imageName: "ubuntu-20.04"
        python.version: "3.8"
        tox.env: py38
        RUN_MEMORY: "true"
      linux-py37:
        imageName: "ubuntu-20.04"
        python.version: "3.7"
        tox.env: py37

  pool:
    vmImage: $(imageName)
  variables:
    JUNITXML: 'test-data.xml'
    PYTEST_ARGS: '-vl --timeout=60 --maxfail=5'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'
    # azure-pipelines unpredictably switches between Git\bin\bash and
    # Git\usr\bin\bash when running a bash script inside Windows environments.
    # The latter may use wrong bash commands, resulting in errors when codecov
    # tries to upload the coverage results.
    - bash: echo "##vso[task.prependpath]C:/Program Files/Git/bin"
      displayName: 'Override Git bash shell for Windows'
      condition: eq(variables['Agent.OS'], 'Windows_NT')

    - script: python -m pip install --upgrade tox
      displayName: 'Install tox'

    - script: |
        bash continuous_integration/runtests.sh
      displayName: 'Test loky'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '$(JUNITXML)'
      displayName: 'Publish Test Results'
      condition: succeededOrFailed()

    - bash: |
        curl -s https://codecov.io/bash | bash
      displayName: 'Upload to codecov'
      condition: and(succeeded(), ne(variables['joblib.tests'], 'true'))
