jobs:
- job: 'test_loky'
  strategy:
    matrix:
      linux-python-nightly:
        imageName: "ubuntu-16.04"
        python.version: "3.9"
        tox.env: py39
      linux-py37:
        imageName: "ubuntu-16.04"
        python.version: "3.7"
        tox.env: py37

  pool:
    vmImage: $(imageName)
  variables:
    JUNITXML: 'test-data.xml'
    PYTEST_ARGS: '-vl --timeout=60 --maxfail=5'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'
      condition: ne(variables['python.version'], '3.9')
    - bash: |
        sudo add-apt-repository ppa:deadsnakes/nightly
        sudo apt update
        sudo apt install python3.9 python3.9-venv python3.9-dev
        python3.9 -m venv nightly-venv
        echo "##vso[task.prependpath]nightly-venv/bin"
      displayName: Install Python 3.9 from ppa:deadsnakes/nightly
      condition: eq(variables['python.version'], '3.9')
    # azure-pipelines unpredictably switches between Git\bin\bash and
    # Git\usr\bin\bash when running a bash script inside Windows environments.
    # The latter may use wrong bash commands, resulting in errors when codecov
    # tries to upload the coverage results.
    - bash: echo "##vso[task.prependpath]C:/Program Files/Git/bin"
      displayName: 'Override Git bash shell for Windows'
      condition: eq(variables['Agent.OS'], 'Windows_NT')

    - script: python -m pip install --upgrade tox
      displayName: 'Install tox'

    - script: |
        bash continuous_integration/runtests.sh
      displayName: 'Test loky'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '$(JUNITXML)'
      displayName: 'Publish Test Results'
      condition: succeededOrFailed()

    - bash: |
        curl -s https://codecov.io/bash | bash
      displayName: 'Upload to codecov'
      condition: and(succeeded(), ne(variables['joblib.tests'], 'true'))
