# Adapted from https://github.com/pandas-dev/pandas/blob/master/azure-pipelines.yml
jobs:

- template: continuous_integration/azure/windows.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016
    matrix:
      py37_conda:
        VERSION_PYTHON: '3.7'
        PACKAGER: 'conda'
      py36_pip:
        VERSION_PYTHON: '3.6'
        PACKAGER: 'pip'
      py35_conda:
        VERSION_PYTHON: '3.5'
        PACKAGER: 'conda'
      py27_pip:
        VERSION_PYTHON: '2.7'
        PACKAGER: 'pip'



# - template: build_tools/azure/posix.yml
#   parameters:
#     name: Linux
#     vmImage: ubuntu-16.04
#     matrix:
#       # Linux environment to test that scikit-learn can be built against
#       # versions of numpy, scipy with ATLAS that comes with Ubuntu Xenial 16.04
#       # i.e. numpy 1.11 and scipy 0.17
#       py35_np_atlas:
#         DISTRIB: 'ubuntu'
#         PYTHON_VERSION: '3.5'
#         SKLEARN_SITE_JOBLIB: '1'
#         JOBLIB_VERSION: '0.11'
#       # Linux + Python 3.5 build with OpenBLAS and without SITE_JOBLIB
#       py35_conda_openblas:
#         DISTRIB: 'conda'
#         PYTHON_VERSION: '3.5'
#         INSTALL_MKL: 'false'
#         NUMPY_VERSION: '1.11.0'
#         SCIPY_VERSION: '0.17.0'
#         CYTHON_VERSION: '*'
#         PILLOW_VERSION: '4.0.0'
#         COVERAGE: 'true'
#       # Linux environment to test the latest available dependencies and MKL.
#       # It runs tests requiring pandas and PyAMG.
#       # It also runs with the site joblib instead of the vendored copy of joblib.
#       pylatest_conda:
#         DISTRIB: 'conda'
#         PYTHON_VERSION: '*'
#         INSTALL_MKL: 'true'
#         NUMPY_VERSION: '*'
#         SCIPY_VERSION: '*'
#         PANDAS_VERSION: '*'
#         CYTHON_VERSION: '*'
#         PYAMG_VERSION: '*'
#         PILLOW_VERSION: '*'
#         JOBLIB_VERSION: '*'
#         COVERAGE: 'true'
#         CHECK_PYTEST_SOFT_DEPENDENCY: 'true'
#         TEST_DOCSTRINGS: 'true'
#         SKLEARN_SITE_JOBLIB: '1'
#         CHECK_WARNINGS: 'true'

# - template: build_tools/azure/posix.yml
#   parameters:
#     name: macOS
#     vmImage: xcode9-macos10.13
#     matrix:
#       pylatest_conda:
#         DISTRIB: 'conda'
#         PYTHON_VERSION: '*'
#         INSTALL_MKL: 'true'
#         NUMPY_VERSION: '*'
#         SCIPY_VERSION: '*'
#         CYTHON_VERSION: '*'
#         PILLOW_VERSION: '*'
#         JOBLIB_VERSION: '*'
#         COVERAGE: 'true'
