language: python
# make it explicit that we favor the new container-based travis workers
sudo: false

env:
  global:
    - PYTHON="python"
matrix:
  include:
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: "nightly"
    - os: osx
      osx_image: xcode7.3
      language: generic  # https://github.com/travis-ci/travis-ci/issues/2312
    - os: osx
      osx_image: xcode7.3
      language: generic  # https://github.com/travis-ci/travis-ci/issues/2312
      env: PYTHON="python3"


before_install:
  - |
    # Install python using brew on OSX
    if [ $TRAVIS_OS_NAME == 'osx' ] && [ $PYTHON == 'python3' ]; then
      brew update
      brew install $PYTHON
    fi

install: ./continuous_integration/install.sh
script: ./continuous_integration/test_script.sh
after_success:
  - pip install codecov
  - codecov

notifications:
  webhooks:
    on_success: change
    # options: [always|never|change] default: always
    on_failure: always
    # options: [always|never|change] default: always
    on_start: never
    # options: [always|never|change] default: always
