language: python
# make it explicit that we favor the new container-based travis workers
sudo: false

env:
  global:
    - PYTHON="python"
    - OMP_NUM_THREADS=4
matrix:
  include:
    - python: 2.7
      env: TOXENV="py27"
    - python: 3.3
      env: TOXENV="py33"
    - python: 3.4
      env: TOXENV="py34"
    - python: 3.5
      env: TOXENV="py35"
    - python: "3.6-dev"
      env: TOXENV="py36"
    - os: osx
      osx_image: xcode7.3
      language: generic  # https://github.com/travis-ci/travis-ci/issues/2312
      env: TOXENV="py27"
      compiler: gcc
    - os: osx
      osx_image: xcode7.3
      language: generic  # https://github.com/travis-ci/travis-ci/issues/2312
      env: TOXENV="py35" PYTHON="python3"

before_install:
  - |
    # Install python using brew on OSX
    if [ $TRAVIS_OS_NAME == 'osx' ] && [ $PYTHON == 'python3' ]; then
      brew update
      brew install $PYTHON
    fi

install: pip install tox
script: ./continuous_integration/travis/runtests.sh
after_success:
  - pip install codecov
  - codecov

notifications:
  webhooks:
    on_success: change
    # options: [always|never|change] default: always
    on_failure: always
    # options: [always|never|change] default: always
    on_start: never
    # options: [always|never|change] default: always
