environment:
  # There is no need to run the build for all the Python version /
  # architectures combo as the generated joblib wheel is the same on all
  # platforms (universal wheel).
  # We run the tests on 2 different target platforms for testing purpose only.
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
matrix:
  fast_finish: true

install:
  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - ps: ./continuous_integration/appveyor/install.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install tox"

# Not a .NET project, we build in the install step instead
build: false

test_script:
  - powershell ./continuous_integration/appveyor/runtests.ps1

on_success:
  # Each toxenv will append its own coverage data to the toplevel
  # .coverage file which is then converted to XML for uploading by codecov
  - "pip install coverage codecov"
  - "codecov"
