#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'tox==2.3.1','console_scripts','tox'
__requires__ = 'tox==2.3.1'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('tox==2.3.1', 'console_scripts', 'tox')()
    )
