#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'console_scripts','tox'
__requires__ = 'tox'

import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('tox', 'console_scripts', 'tox')()
    )
