name: CI
permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # Weekly build on Tuesday at 2:00 AM
    - cron: "0 2 * * 2"

# Cancel in-progress workflows when pushing
# a new commit on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.10.0
        with:
          pixi-version: v0.76.2
          environments: lint
          cache: true
          locked: true
      - name: Run black
        run: pixi run --locked --environment lint lint

  testing:
    name: Testing
    needs: linting
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: windows-py314
            os: windows-latest
            PIXI_ENVIRONMENT: py314
            PIXI_TASK: test
          - name: windows-py313
            os: windows-latest
            PIXI_ENVIRONMENT: py313
            PIXI_TASK: test
          - name: windows-py310
            os: windows-latest
            PIXI_ENVIRONMENT: py310
            PIXI_TASK: test
            LOKY_TEST_NO_CIM: "true"

          - name: macos-py314
            os: macos-latest
            PIXI_ENVIRONMENT: py314
            PIXI_TASK: test
          - name: macos-py313
            os: macos-latest
            PIXI_ENVIRONMENT: py313
            PIXI_TASK: test
          - name: macos-py310
            os: macos-latest
            PIXI_ENVIRONMENT: py310
            PIXI_TASK: test

          - name: linux-py314-free-threading
            os: ubuntu-latest
            PIXI_ENVIRONMENT: py314-free-threaded
            PIXI_TASK: test
          - name: linux-py313
            os: ubuntu-latest
            PIXI_ENVIRONMENT: py313-viztracer
            PIXI_TASK: test
            LOKY_TEST_NO_LSCPU: "true"
          - name: linux-py310-joblib-tests
            os: ubuntu-latest
            PIXI_ENVIRONMENT: joblib-py310
            PIXI_TASK: test-joblib
            JOBLIB_TESTS: "true"
          - name: linux-python-py310-high-memory
            os: ubuntu-latest
            PIXI_ENVIRONMENT: py310
            PIXI_TASK: test-high-memory
          - name: linux-py310
            os: ubuntu-latest
            PIXI_ENVIRONMENT: py310-no-psutil
            PIXI_TASK: test
            # Do not install psutil on Python 3.10 to have some CI runs that
            # tests that loky has no hard dependency on psutil.
            NO_PSUTIL: "true"

    env: ${{ matrix }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.10.0
        with:
          pixi-version: v0.76.2
          environments: ${{ matrix.PIXI_ENVIRONMENT }}
          cache: true
          locked: true

      - name: Run tests
        run: pixi run --locked --environment ${{ matrix.PIXI_ENVIRONMENT }} ${{ matrix.PIXI_TASK }}

      - name: Upload to Codecov
        # always upload coverage even if tests fail
        if: ${{ matrix.JOBLIB_TESTS != 'true' && (success() || failure()) }}
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
